---
#System installed with ansible-galaxy collection cisco.intersight
- hosts: "localhost"
  connection: local
  gather_facts: false
  vars:
    #Enter the location of secret.txt with Intersight Secret Key
    api_private_key: "/home/PODX/intersight-rest-api/secret.txt"
    #Enter the API Key ID from Intersight
    api_key_id: "61e075b87564612d33952212/61e5a6c57564612d30792496/620562087564612d301e72fc"
    #Enter the Organization, Replace X with POD number
    org_name: PODX
    # Enter the Policy Name, Replace X with POD number
    policy_name: PODX-ntp-policy
    # present for Create/Update Policy.absent for delete Policy
    ops: present
  tasks:
    - name: Configure NTP Policy
      cisco.intersight.intersight_ntp_policy:
         api_private_key: "{{ api_private_key }}"
         api_key_id: "{{ api_key_id }}"
         organization: "{{ org_name }}" 
         name: "{{ policy_name }}"
         description: NTP policy using Ansible.
         ntp_servers:
            - pool.ntp.org
         timezone: America/Los_Angeles 
         state: "{{ ops }}" 
